spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/menu
    username: postgres
    password: 123456llg

  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
